

service: authentication-cognito # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev

functions:
  verifyToken:
    handler: handler.verifyToken
    integration: lambda
  getItem:
    handler: handler.getItem
    events:
      - http:
          path: /item
          method: get
          
  resources:
    Resources:
      CognitoUserpool:
        Type: AWS::Cognito::Userpool
        Properties:
          UserPoolName: headlight_user_pool
      CognitoUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
          ClientName: headlight_client
          UserPoolId:
            Ref: CognitoUserpool
      CognitoUserPoolDomainName:
        Type: Custom::CognitoUserPoolDomain
        Properties:
           UserPoolId:
            Ref: CognitoUserpool
            Domain: 'test-headlight-01'
      CognitoUserPoolClient:
        Type: 'Custom::CognitoUserPoolClientSettings'
        Properties:
          UserPoolId:
            Ref: CognitoUserpool
          UserPoolClientId:
            Ref: CognitoUserPoolClient
          SupportedIdentityProviders:
            - SAML
          CallbackURL: 'https://www.amazon.com'
          LogoutURL: 'https://www.google.com'
          AllowedOAuthFlowsUserPoolClient: true
          AllowedOAuthFlows:
             - code
          AllowedOAuthScopes:
             - openid



